import type { Metadata } from "next";
import "@/app/globals.css";
import NavBar from "@/app/ui/NavBar";
import ReactQueryProvider from "./Provider/ReactQueryProvider";
import { leagueSpartan } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={leagueSpartan.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
